### ISSUE TITLE
What does `TLSCLaims` mean?

### ISSUE THREAD

**Issue by marek22k** [michael-lazar/gemini-diagnostics#10]
I get
```
[TLSClaims] Certificate claims must be valid
  x 'Backend' object has no attribute 'load_der_x509_certificate'
```
during the test. What does it mean?

**Comment by michael-lazar** [comment]
Hmm I see the same error, it looks like the `cryptography` library changed their public API and the code needs to be updated.

```
$ python3 -m pip freeze | grep cryptography
cryptography==37.0.4
```

**Comment by michael-lazar** [comment]
Fixed in https://github.com/michael-lazar/gemini-diagnostics/commit/598da6b2828ab4e9c179eb0af53555994d961b5c
