### ISSUE TITLE
Return error if tests fail

### ISSUE THREAD

**Issue by tinywombat765** [michael-lazar/gemini-diagnostics#3]
It's be helpful if test script returned 1 or something when it exited if any tests failed so it could be used as an automated test.  I'm planning to implement this myself but was wondering if you had any suggestions on how to go about it.  I haven't looked through your code much yet.

**Comment by tinywombat765** [comment]
Maybe add a success param to BaseCheck, make log_test, log_error and the assert functions methods and make them flip the success param

**Comment by michael-lazar** [comment]
I think that's a fine idea. It feels a little hacky, but then again the whole script feels a little hacky 🤷‍♂️ 

Added in e7704294b13f455b368b29759fe33e6ace2543b1
